name: "Release to GHCR"
description: "Republish a Docker Image, with a known SHA, from Apollo's internal repositories to GHCR"
inputs:
  image_name:
    description: 'The name of the Docker Image that is to be built'
    required: true
  commit_sha:
    description: "The commit SHA of the image to re-publish"
    required: true
  version_number:
    description: "The version number that is to be used for the release"
    required: true
outputs: {}

runs:
  using: composite
  steps:
    - name: Authenticate With GCP
      id: gcp-auth
      uses: 'google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093'
      with:
        token_format: 'access_token'
        project_id: "${{ secrets.PUBLISHING_SERVICE_ACCOUNT_PROJECT_ID }}"
        service_account: "${{ secrets.PUBLISHING_SERVICE_ACCOUNT_NAME }}"
        workload_identity_provider: "${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}"
    - name: Authenticate With Internal Repository
      id: docker-auth
      uses: 'docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef'
      with:
        username: 'oauth2accesstoken'
        password: '${{ steps.gcp-auth.outputs.access_token }}'
        registry: '${{ secrets.BASE_ARTIFACT_REGISTRY_NAME }}'
    - name: Log in to GHCR
      uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f
    - name: "Ensure correct name"
      id: ensure-correct-name
      run: |
        REPO_NAME=$(echo ${{ github.repository }} | cut -d '/' -f 2)
        if [[ "$REPO_NAME" == "${{ inputs.image_name }}" ]]; then
          echo "CORRECTED_IMAGE_NAME=ghcr.io/${{ github.repository }}" >> "${GITHUB_OUTPUT}"
        else
          echo "CORRECTED_IMAGE_NAME=ghcr.io/${{ github.repository }}/${{ inputs.image_name }}" >> "${GITHUB_OUTPUT}"
        fi
      shell: bash
    - name: "Retag and push image to GHCR"
      run: |
        NEW_TAG=${{ steps.ensure-correct-name.outputs.CORRECTED_IMAGE_NAME }}:${{ inputs.version_number }}
        docker buildx imagetools create -t $NEW_TAG ${{ secrets.APOLLO_ARTIFACT_REGISTRY }}/${{ inputs.image_name }}:${{ inputs.commit_sha }}
      shell: bash
